### ISSUE TITLE
multiCheckbox does not initialize state

### ISSUE THREAD

**Issue by sjerman** [formly-js/angular-formly-templates-bootstrap#10]
Unless I am missing something (which of cause may well be the case). the multiCheckbox type doesn't initialize with the modelObject contents.

**Comment by kentcdodds** [comment]
I'm not sure I understand what you mean. Could you show me an example of what you're talking about? http://jsbin.com/biqesi/edit

**Comment by sjerman** [comment]
OK.. here you go.
http://jsbin.com/wimiluxita/3/
.. the fix is in the comments :)

**Comment by kentcdodds** [comment]
Good find! Until I get a chance to update this repo, you can [use this](http://jsbin.com/capiqo/2/edit) as a workaround. Feel free to make your own PR. It would amount to adding this to [this line](https://github.com/formly-js/angular-formly-templates-bootstrap/blob/master/src/types/multiCheckbox.js#L26)

**Comment by kentcdodds** [comment]
This has been fixed in 4.0.4. Thanks!
http://jsbin.com/kavoge/1/edit?html,js,output

**Comment by sjerman** [comment]
Hi. Just wanted to say thanks. I'm very impressed with the module.

Steve

**Comment by kentcdodds** [comment]
I really appreciate that :-) Keeps me going! Thanks!

**Comment by sjerman** [comment]
Hi,

I did a custom template (extending one of you examples) to use ui-select as
a dropdown.

http://jsbin.com/wosetepeva/7/

Not sure if these examples are of use to you .. I'll probably do more as I
work through my use cases..

Let me know if yu want me to send them to you...

Steve

**Comment by kentcdodds** [comment]
That's awesome! The more examples, the better :-) Thanks!

Looks like you created that jsbin anonymously, so I cloned it, and it appears that it's not working as expected. If I choose something from ui-select, it doesn't stay selected. Is that what you saw?

Here's my clone: http://jsbin.com/casino/1/edit?html,js,output

**Comment by sjerman** [comment]
Ok, well I figured my previous issue ... updated version of module and
caching...

The real implementation of the jsbin is working correctly. I'll have
another look at the one I sent.

Steve
