### ISSUE TITLE
Avoid of overwriting angular-formly-templates-bootstrap over my default bootstrapt

### ISSUE THREAD

**Issue by maryampashmi** [formly-js/angular-formly-templates-bootstrap#11]
Hi, 
In my app, i have used bootstrapt from https://bootswatch.com/. After adding angular-formly-templates-bootstrap to my app i lost default colors for my app. I would like to come back to my original bootstrapt therefore i  removed angular-formly-templates-bootstrap from index.html but angular formy doesn't work anymore. What is the solution in order to keep my original bootstrapt color and also i use angular formly?

Thank you.

**Comment by kentcdodds** [comment]
I'm not sure this is a real bug with these templates. I'm going to go ahead and close this. Feel free to open this if you have something reproducible. Thanks.

**Comment by maryampashmi** [comment]
Hello Kent.  
I know this is not a bug but I didn't find any place to ask my question about formly. 
I would like to know if I can use formly template and to keep my boot strap default.  Because using formly imediately change all colours and fonts to its default.  I still have this problem and I don't know how to deal with that.

**Comment by kentcdodds** [comment]
I think this question would be best asked on StackOverflow.

**Comment by maryampashmi** [comment]
I couldn't get any answer anywhere. I tried all before. That's why i put my question here. 
Anyway, thank you. I should use other solution instead of angular-formly ;)

**Comment by kentcdodds** [comment]
Instead, you could simply write your own templates. It's very easy to do. You could use this repo as an example.

**Comment by kentcdodds** [comment]
And again, I'm certain that it's not a problem with angular-formly-templates-bootstrap. I can't think of any way that it could be remotely responsible. But if your only recourse is to use something else, then I'm sorry about that...

**Comment by maryampashmi** [comment]
ok.  hope to find solution as i like angular -formly.
