### ISSUE TITLE
Remove/more lenient angular peerDependencies entry

### ISSUE THREAD

**Issue by pmowrer** [formly-js/angular-formly-templates-bootstrap#12]
Directly related to the resolution of https://github.com/formly-js/angular-formly/issues/235.

Is `angular` a necessary explicit dependency for formly templates? Since `angular-formly` is already a dependency, the `angular` dependency is implied.

**Comment by kentcdodds** [comment]
Hmmm... Good point. Not sure if the "correct" way to do this... What do you
think?

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by pmowrer** [comment]
Yeah, not sure what's "correct" either. Keeping the peerDependency is probably safest, though, I would imagine, a pain to keep in sync. The other option would be to leave it out of dependencies entirely and explicitly require it via `angular-formly` e.g.:

`require('angular-formly/node_modules/angular')`

**Comment by kentcdodds** [comment]
I think that because the template library explicitly requires both angular and api-check, I'm going to leave them as peerDependencies. I'll have a fix out soon.
