### ISSUE TITLE
Missing file error when running tests

### ISSUE THREAD

**Issue by astrism** [formly-js/angular-formly-templates-bootstrap#14]
When I run `npm run start` I get the following error. As far as I can tell `./run/index.test` isn't in the repo.
```
ERROR in ./src/index.test.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./run/index.test in /Users/grant/Git/angular-formly-templates-bootstrap/src
 @ ./src/index.test.js 10:0-27
webpack: bundle is now VALID.
Chrome 41.0.2272 (Mac OS X 10.10.3) ERROR
  Uncaught TypeError: undefined is not a function
  at /Users/grant/Git/angular-formly-templates-bootstrap/src/index.test.js:79
```

**Comment by kentcdodds** [comment]
Sorry, TBH, this repo doesn't really have much love. I pretty much just make my changes and run `npm run build`. Lots of the scripts in there are copy/paste... Feel free to PR.

**Comment by astrism** [comment]
Fair enough, I'll try that out :)

**Comment by kentcdodds** [comment]
Feel free to take a look at how the angular-formly build works. It should be very similar. Let me know if you have any questions. And it's nice to hear from you again @astrism :-) Going to be using formly again I take it?

**Comment by astrism** [comment]
Definitely still using it quite a bit, I'll see what i can do to help :smile:

**Comment by kentcdodds** [comment]
I hope that you've been able to take advantage of the changes I've made in the last few months :-) Thanks for the help!

**Comment by kentcdodds** [comment]
So I just released a beta version of [kcd-common-tools](https://github.com/kentcdodds/kcd-common-tools) which I implemented on `angular-formly` and plan to implement here. It should (hopefully) make tooling setup much easier for all of the formly projects. I'll implement it as soon as I am able.

**Comment by Cabeza** [comment]
Im trying to run `npm run build` but got this error msg:

```
✘  derlisgarcete@Derliss-MacBook-Air  ~/WebstormProjects/angular-formly-templates-bootstrap   master  npm run build

> angular-formly-templates-bootstrap@6.1.0 build /Users/derlisgarcete/WebstormProjects/angular-formly-templates-bootstrap
> npm run build:dist; npm run build:minify


> angular-formly-templates-bootstrap@6.1.0 build:dist /Users/derlisgarcete/WebstormProjects/angular-formly-templates-bootstrap
> webpack

building version 6.1.0
Webpack config is in dev mode
Hash: e6fb25a7bc48d49bb7a2
Version: webpack 1.12.2
Time: 1046ms
    + 1 hidden modules

ERROR in ./index.js
Module build failed: Error: "../index.js" is not in the SourceMap.
    at SourceMapConsumer_sourceContentFor [as sourceContentFor] (/Users/derlisgarcete/WebstormProjects/angular-formly-templates-bootstrap/node_modules/ng-annotate-loader/node_modules/source-map/lib/source-map/source-map-consumer.js:697:15)
    at SourceMapGenerator.<anonymous> (/Users/derlisgarcete/WebstormProjects/angular-formly-templates-bootstrap/node_modules/ng-annotate-loader/node_modules/source-map/lib/source-map/source-map-generator.js:233:42)
    at Array.forEach (native)
    at SourceMapGenerator_applySourceMap [as applySourceMap] (/Users/derlisgarcete/WebstormProjects/angular-formly-templates-bootstrap/node_modules/ng-annotate-loader/node_modules/source-map/lib/source-map/source-map-generator.js:232:34)
    at Object.module.exports (/Users/derlisgarcete/WebstormProjects/angular-formly-templates-bootstrap/node_modules/ng-annotate-loader/loader.js:20:17)

> angular-formly-templates-bootstrap@6.1.0 build:minify /Users/derlisgarcete/WebstormProjects/angular-formly-templates-bootstrap
> webpack --config webpack.config.minify.js

building version 6.1.0
Webpack config is in dev mode
Webpack config is in prod mode
Hash: 53bf439f1034869638ad
Version: webpack 1.12.2
Time: 1020ms
    + 1 hidden modules

ERROR in ./index.js
Module build failed: Error: "../index.js" is not in the SourceMap.
    at SourceMapConsumer_sourceContentFor [as sourceContentFor] (/Users/derlisgarcete/WebstormProjects/angular-formly-templates-bootstrap/node_modules/ng-annotate-loader/node_modules/source-map/lib/source-map/source-map-consumer.js:697:15)
    at SourceMapGenerator.<anonymous> (/Users/derlisgarcete/WebstormProjects/angular-formly-templates-bootstrap/node_modules/ng-annotate-loader/node_modules/source-map/lib/source-map/source-map-generator.js:233:42)
    at Array.forEach (native)
    at SourceMapGenerator_applySourceMap [as applySourceMap] (/Users/derlisgarcete/WebstormProjects/angular-formly-templates-bootstrap/node_modules/ng-annotate-loader/node_modules/source-map/lib/source-map/source-map-generator.js:232:34)
    at Object.module.exports (/Users/derlisgarcete/WebstormProjects/angular-formly-templates-bootstrap/node_modules/ng-annotate-loader/loader.js:20:17)
```

**Comment by kentcdodds** [comment]
I made some changes last night. Do you have those latest changes? When did
you come the repo?

On Sat, Sep 26, 2015, 10:16 AM Cabeza <notifications@github.com> wrote:

> Im trying to run npm run build but got this error msg:
>
> ✘  derlisgarcete@Derliss-MacBook-Air  ~/WebstormProjects/angular-formly-templates-bootstrap   master  npm run build
>
> > angular-formly-templates-bootstrap@6.1.0 build /Users/derlisgarcete/WebstormProjects/angular-formly-templates-bootstrap
> > npm run build:dist; npm run build:minify
>
>
> > angular-formly-templates-bootstrap@6.1.0 build:dist /Users/derlisgarcete/WebstormProjects/angular-formly-templates-bootstrap
> > webpack
>
> building version 6.1.0
> Webpack config is in dev mode
> Hash: e6fb25a7bc48d49bb7a2
> Version: webpack 1.12.2
> Time: 1046ms
>     + 1 hidden modules
>
> ERROR in ./index.js
> Module build failed: Error: "../index.js" is not in the SourceMap.
>     at SourceMapConsumer_sourceContentFor [as sourceContentFor] (/Users/derlisgarcete/WebstormProjects/angular-formly-templates-bootstrap/node_modules/ng-annotate-loader/node_modules/source-map/lib/source-map/source-map-consumer.js:697:15)
>     at SourceMapGenerator.<anonymous> (/Users/derlisgarcete/WebstormProjects/angular-formly-templates-bootstrap/node_modules/ng-annotate-loader/node_modules/source-map/lib/source-map/source-map-generator.js:233:42)
>     at Array.forEach (native)
>     at SourceMapGenerator_applySourceMap [as applySourceMap] (/Users/derlisgarcete/WebstormProjects/angular-formly-templates-bootstrap/node_modules/ng-annotate-loader/node_modules/source-map/lib/source-map/source-map-generator.js:232:34)
>     at Object.module.exports (/Users/derlisgarcete/WebstormProjects/angular-formly-templates-bootstrap/node_modules/ng-annotate-loader/loader.js:20:17)
>
> > angular-formly-templates-bootstrap@6.1.0 build:minify /Users/derlisgarcete/WebstormProjects/angular-formly-templates-bootstrap
> > webpack --config webpack.config.minify.js
>
> building version 6.1.0
> Webpack config is in dev mode
> Webpack config is in prod mode
> Hash: 53bf439f1034869638ad
> Version: webpack 1.12.2
> Time: 1020ms
>     + 1 hidden modules
>
> ERROR in ./index.js
> Module build failed: Error: "../index.js" is not in the SourceMap.
>     at SourceMapConsumer_sourceContentFor [as sourceContentFor] (/Users/derlisgarcete/WebstormProjects/angular-formly-templates-bootstrap/node_modules/ng-annotate-loader/node_modules/source-map/lib/source-map/source-map-consumer.js:697:15)
>     at SourceMapGenerator.<anonymous> (/Users/derlisgarcete/WebstormProjects/angular-formly-templates-bootstrap/node_modules/ng-annotate-loader/node_modules/source-map/lib/source-map/source-map-generator.js:233:42)
>     at Array.forEach (native)
>     at SourceMapGenerator_applySourceMap [as applySourceMap] (/Users/derlisgarcete/WebstormProjects/angular-formly-templates-bootstrap/node_modules/ng-annotate-loader/node_modules/source-map/lib/source-map/source-map-generator.js:232:34)
>     at Object.module.exports (/Users/derlisgarcete/WebstormProjects/angular-formly-templates-bootstrap/node_modules/ng-annotate-loader/loader.js:20:17)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/formly-js/angular-formly-templates-bootstrap/issues/14#issuecomment-143467754>
> .
>
-- 
- Kent C. Dodds <https://twitter.com/kentcdodds>

**Comment by Cabeza** [comment]
@kentcdodds thanks for your prompt response!  its working great now!  thank you!
