### ISSUE TITLE
'Types' directory not ngTemplated

### ISSUE THREAD

**Issue by sjerman** [formly-js/angular-formly-templates-bootstrap#15]
I *think* that the types directory needs to be included here ..

... my production build does not load the multiCheckbox ... I think it's because the template isn't being processed.

Steve

    ngtemplates: {
    ...
    files: [
        {
            cwd: preBuiltDest + '/',
            src: ['fields/**/*.html', 'wrappers/**/*.html', 'other/**/*.html'],
            dest: templatesFile
          }
        ]
      }
    },

**Comment by kentcdodds** [comment]
That appears to be the old Grunt build. We no longer use grunt, but webpack, and we don't have a need for this config.

**Comment by sjerman** [comment]
ah!

OK ... that explains it. Will look again :)

Steve
