### ISSUE TITLE
Select form field not working

### ISSUE THREAD

**Issue by luckylooke** [formly-js/angular-formly-templates-bootstrap#16]
seems to be not connected to model see bin here: http://jsbin.com/yimogo/1/edit?js,output
try change Hot Air Baloon to another value.
(select example copied from documentation)

**Comment by kentcdodds** [comment]
Sorry, the example needed to specify a `valueProp`. Thanks for the issue!

**Comment by luckylooke** [comment]
Thanks for quick response :)
