### ISSUE TITLE
Radio and multi checkbox types do not receive formControl or errorExistsAndShouldBeVisible

### ISSUE THREAD

**Issue by s992** [formly-js/angular-formly-templates-bootstrap#17]
First: I'm not sure if this is specific to this template library or if it's something that should be addressed in the main Formly repo. If you'd like me to migrate this issue to the main repo, please let me know.

Here's a JS Bin showing the issue: http://jsbin.com/naqaqaguma/2/edit

As you can see, my "input" type field received a `formControl` object and the `errorExistsAndShouldBeVisible` key in `validation`. The other two, however, did not.

Through the excessive use of debugger statements, I believe I've located the problem in the `watchFormControl` function in [formly-field.js](https://github.com/formly-js/angular-formly/blob/master/src/directives/formly-field.js#L190). Specifically, the function exits early due to lines [196-199](https://github.com/formly-js/angular-formly/blob/master/src/directives/formly-field.js#L196) because Formly can't locate the `ng-model` attribute in the element. This prevents Formly from adding the `watchFieldExistence` and `addShowMessageWatcher` watchers, which set `formControl` and `errorExistsAndShouldBeVisible`, respectively.

By examining the element at this point in the execution, it appears that the actual inputs have not yet populated via `ng-repeat`, so there is no `ng-model` for Formly to find.

I'm at a bit of a loss with regards to a solution because it seems like it's a timing issue with directive compilation. Perhaps the directive could be compiled prior to Formly starting its watches?

**Comment by kentcdodds** [comment]
What if you were able to set `noFormControl: false` explicitly and that would cause formly to add the watcher anyway. I think this would work. Would that be acceptable?

**Comment by s992** [comment]
Doesn't appear to make a difference - I tried setting it on the field as well as creating a custom type with the option set: http://jsbin.com/tonelumepu/2/edit

**Comment by kentcdodds** [comment]
Sorry, what I meant was, what if I made it work that way (doesn't currently). Do you think that would be a reasonable API to use?

**Comment by s992** [comment]
Sure, that sounds perfectly reasonable.

**Comment by kentcdodds** [comment]
Alrighty, I think I've got it working in angular-formly 6.3.3 and the templates 4.0.8. Let me know if you have trouble!

**Comment by s992** [comment]
Looks to be working well for me, thanks!

**Comment by kentcdodds** [comment]
So, I've figured out a better way to accomplish this. You no longer will need to specify `noFormControl: false` :-) Look forward to angular-formly@6.3.4 :-)
