### ISSUE TITLE
Description not rendered for radio input

### ISSUE THREAD

**Issue by sackerud** [formly-js/angular-formly-templates-bootstrap#18]
Thank you so much for working on this project, it's truly awesome and saves me a lot of time. Keep up the good work.

I can't get the description from the templateOptions on radio input to show up. Works fine on all other input types though. Here's an example: http://jsbin.com/tayucopahu/2/edit?js,output (I just extended one of your examples).

I guess I could make a PR but someone has to point me in the right direction as I'm not that js savvy :). Here's a screenshot of a checkbox- and radio list that both have a description in their templateOptions:
![descmissingonradio](https://cloud.githubusercontent.com/assets/7229490/7489864/7c14582a-f3db-11e4-95e1-1b7a57313e9c.png)

**Comment by sackerud** [comment]
Hmm, after digging a bit I see that descriptions are actively not rendered for checkbox and radio input:
```javascript
if (angular.isDefined(options.templateOptions.description) &&
        options.type !== 'radio' && options.type !== 'checkbox') {
        var el = document.createElement('div');
        el.appendChild(angular.element(template)[0]);
        var modelEls = angular.element(el.querySelectorAll('[ng-model]'));
        if (modelEls) {
          el.appendChild(angular.element(
            '<p id="' + scope.id + '_description"' +
            'class="help-block"' +
            'ng-if="to.description">' +
            '{{to.description}}' +
            '</p>'
          )[0]);
...
```
Copied from [description.js](https://github.com/formly-js/angular-formly-templates-bootstrap/blob/master/src/run/description.js)
Why are descriptions omitted on checkbox and radio inputs?

**Comment by kentcdodds** [comment]
You know what, I think there shouldn't be a problem to allow them for all fields. I'll push an update soon.

**Comment by kentcdodds** [comment]
Your example now works with 4.0.9 :-)

**Comment by sackerud** [comment]
Truly epic Kent. I get a fix on the issue the same day it is reported. Even though it was not a complicated issue, I'm still amazed about the speedy fix. I'm happily upgrading to 4.0.9!

**Comment by kentcdodds** [comment]
:+1: :-)
