### ISSUE TITLE
Setting required on a multiCheckbox requires all checkboxes to be checked

### ISSUE THREAD

**Issue by sackerud** [formly-js/angular-formly-templates-bootstrap#19]
When setting `required: true` in the templateOptions of a multiCheckbox, the form isn't considered valid until **all** checkboxes are checked. In my opion, the form should be considered valid when at least one the checkboxes are checked.

See an example on jbin here: http://jsbin.com/poxicexafa/2/edit?html,js,output

**Comment by kentcdodds** [comment]
There's not a way to accomplish this using normal angular with the `required` attribute because there's no way to group checkboxes in angular (as in, without angular-formly). So your solution will be a custom validator that does this checking for you.

**Comment by sackerud** [comment]
I see. Better write my own custom validator then.

**Comment by kentcdodds** [comment]
Let me know if you need assistance.

**Comment by kentcdodds** [comment]
I noticed that the multi-checkbox has some trouble with the form control so `$viewValue` and `$modelValue` aren't quite right. I'm not certain how to fix this issue. It's kind of a limitation with how checkboxes work (not normally grouped together like that). I'll see if I can think of something that will work well, but for now I think you may have a hard time. Reopening... Please let me know if you get something figured out.

**Comment by sackerud** [comment]
Correct me if I'm wrong. A custom validator has only access to its own form element properties, right? If so, the only solution I can think of is to grab the parent (`<div class="radio-group">`) and from there find out if any child checkboxes are checked. But that solution is quite dirty.

Could we make use of ng-required? Here's solution to a similar problem: http://stackoverflow.com/a/19633860/588059

**Comment by kentcdodds** [comment]
it's actually already using `ng-required` but it's applying it to all `ng-model` elements. I'm going to close this in favor of https://github.com/formly-js/angular-formly/issues/275 because this is an angular-formly core issue.

You may be able to get a work-around to work by creating a custom directive that takes only one `ng-model` and the directive itself will use multiple `ng-model`s

**Comment by kentcdodds** [comment]
@ckniffen and @Den-dp were having a talk on [the Gitter chat](http://gitter.im/formly-js/angular-formly) today about this same issue. @ckniffen created [an example](http://jsfiddle.net/W99rX/) of a directive that could do this. Thanks!

**Comment by ckniffen** [comment]
Actually I can't take credit for that example I just found it online.

**Source**: http://stackoverflow.com/questions/25141773/angularjs-bind-one-ng-model-to-directive-with-two-inputs

**Comment by sackerud** [comment]
I feel stupid. How does the example apply to a "required" multiCheckbox in formly? Sorry guys, this is my first encounter with angular.

**Comment by tb** [comment]
Following code allowed me to require at least one checked item instead of all items selected:

        $scope.multiCheckbox = {
          checked: [],
          hasChecked: hasChecked,
          change: setModel,
        };
        ...
        function hasChecked() {
          return $scope.multiCheckbox.checked.indexOf(true) > -1;
        }
        ...

And in the template:

        ng-required="!multiCheckbox.hasChecked()"

Based on: http://stackoverflow.com/questions/19632933/angularjs-group-check-box-validation

**Comment by kentcdodds** [comment]
Nice! Thanks for the code example :D

**Comment by SabariRaja27** [comment]
hi all..is this issue got fixed?...I'm also facing the same issue for check boxes.whether i should create a new customised directory?.Did any one tried the directory??

**Comment by WorkMAE** [comment]
Late to the party, but I was having an issue with the same thing dealing with a custom template of multi-checkboxes inline and this works for me:

 ```
                         expressionProperties: {
                                'templateOptions.required': function($viewValue, $modelValue, $scope){
                                    //returns false if any values have been selected, true otherwise
                                    if($scope.model.accountTypes !== undefined) {
                                    return Object.keys($scope.model.accountTypes).every(function (k) { return $scope.model.accountTypes[k] !== true } );
                                   };
                                }
                            }
```

It sets required to true if the object has no true property and to false otherwise(I have an object with properties, not an array).  This could also be put in the TemplateOptions onChange property and just change $scope.to.required directly, but I think this is more the appropriate solution
