### ISSUE TITLE
Error: npm install angular-formly angular-formly-templates-bootstrap --save

### ISSUE THREAD

**Issue by neilyoung** [formly-js/angular-formly-templates-bootstrap#20]
npm ERR! peerinvalid The package angular-formly does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer angular-formly-templates-bootstrap@4.0.9 wants angular-formly@>=4.0.5

129 verbose stack Error: The package angular-formly does not satisfy its siblings' peerDependencies requirements!
129 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:125:32
129 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:267:7
129 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:138:5
129 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:251:14
129 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
129 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:251:14
129 verbose stack     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:27:18)
129 verbose stack     at next (/usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:222:5)
129 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:175:7
129 verbose stack     at LOOP (evalmachine.<anonymous>:1474:14)

Any ideas?

**Comment by kentcdodds** [comment]
Make sure you install angular-formly first.

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by neilyoung** [comment]
Did that before posting. Initially I followed the instructions regarding how to get started. Then tried to install the bootstrap templates. Same result. However, everything seems to wodk well, it just seems to be a config issue.

**Comment by kentcdodds** [comment]
Sorry for not responding to this. Somehow it fell through. Did you get it resolved?

**Comment by neilyoung** [comment]
Oh, I totally forgot about. Thanks for the follow up nevertheless

**Comment by kentcdodds** [comment]
So, is it working now?

**Comment by neilyoung** [comment]
Sorry, can't say that. Didn't try again. Have given up Angular completely (for backward compatibility reasons with IE8)
