### ISSUE TITLE
Problem with 'className' and 'fieldGroup'

### ISSUE THREAD

**Issue by jmsherry** [formly-js/angular-formly-templates-bootstrap#21]
Error: angular-formly: formly-field directive apiCheck failed! `value` at `Argument 1` cannot have extra properties: `className`, `fieldGroup`.It is limited to `$$hashKey`, `type`, <snip>  formly-field-directive-validation-failed

Hi Kent,
I get the above error when I copy and paste the demo code. I'm just trying it out and copying some fields from http://angular-formly.com/#/example/other/advanced-layout . I've checked and it's all included and dependancy injected. To me this looks like the bootstrap properties aren't registered. Does something need to be built maybe?

**Comment by kentcdodds** [comment]
Sorry, those properties are only available in the latest beta release.

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by jmsherry** [comment]
Hi Kent (sorry for the typo :/ ),
Thanks for the quick reply. Do you know when this version will make it to bower?

Thanks

**Comment by kentcdodds** [comment]
Early next week. You can install the beta version explicitly with: bower
install angular-formly@6.4.0-beta.4

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by jmsherry** [comment]
Oh cool! Thanks Kent... :)

**Comment by jmsherry** [comment]
bower                        ENOTFOUND Package angular-formly@6.4.0-beta.4 not found
