### ISSUE TITLE
Formly checkbox and radiobutton look empty

### ISSUE THREAD

**Issue by Najai** [formly-js/angular-formly-templates-bootstrap#24]
Hi,
This issue is aesthetic : the checkbox and radio input fields look always unchecked even if they aren't (screenshot below). We are using angular-formly-templates-bootstrap 4.3.1 with angular-formly 6.10.1 and angular 1.3.15.

Thanks in advance,

![bug formly](https://cloud.githubusercontent.com/assets/10762106/7835877/5e5f1354-047c-11e5-8475-61c463f877b6.png)

**Comment by kentcdodds** [comment]
@Najai, I'm pretty sure that if those checkboxes are supposed to be checked, then you have some other problem. Because they actually look fine in all of [the examples](http://angular-formly.com)

**Comment by Najai** [comment]
It seems that there is a conflict with awsome-bootstrap-checkbox (https://github.com/flatlogic/awesome-bootstrap-checkbox). I have reproduced the bug on jsbin : http://jsbin.com/fiseredavi/2/edit?css,js,output . Now i'll try to figure out why...

**Comment by Najai** [comment]
issue moved on formly : https://github.com/formly-js/angular-formly/issues/323
