### ISSUE TITLE
Improve multi-checkbox `required`

### ISSUE THREAD

**Issue by kentcdodds** [formly-js/angular-formly-templates-bootstrap#26]
Moved from https://github.com/formly-js/angular-formly/issues/330

Original issue by @PhilFlash:

Hi,
Error is incorrect when you use a multicheckbox and option required.
See example:
http://plnkr.co/edit/IleV3U8AVY0Va3lbmUve?p=info

Steps to reproduce:
- step 1 : check Travel and uncheck Travel (last checkbox) => there is an error : Type is required : field is in red : all is ok
- step 2 : check Research => the field Type is in error : BUG

Only the last checkbox is used to check 'Required'

**Comment by kentcdodds** [comment]
Thanks to @ckniffen, this has been fixed and released in 4.3.2

**Comment by kentcdodds** [comment]
cc/ @PhilFlash fixed in 4.3.2 :-)

**Comment by PhilFlash** [comment]
Thanks
