### ISSUE TITLE
One way bindings

### ISSUE THREAD

**Issue by ShMcK** [formly-js/angular-formly-templates-bootstrap#3]
I was thinking of adding more one-way bindings to reduce watchers and increase template performance. Most `templateOptions` would benefit. 

But quick sanity check: are there any use cases where an `id` or `key` would require a two-way binding?

```
<div class="checkbox">
	<label>
		<input type="checkbox"
           class="formly-field-checkbox"
		       id="{{::id}}"
		       formly-dynamic-name="::id"
		       formly-custom-validation="options.validators"
		       aria-describedby="{{::id}}_description"
		       ng-required="::options.templateOptions.required"
		       ng-disabled="::options.templateOptions.disabled"
		       ng-model="::model[options.key]">
		{{::options.templateOptions.label}}
		{{::options.templateOptions.required ? '*' : ''}}
	</label>
</div>
```

**Comment by kentcdodds** [comment]
It's up to you, but the reason I'm not doing one way data bindings now is
so people who are still on 1.2 can use formly. But I can't think of any
other reason not to bind those things once.

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by kentcdodds** [comment]
Also, if you're going to ditch 1.2, then you can also ditch the
formly-dynamic-name and just use a name with an expression like the id :-)

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by ShMcK** [comment]
I'd forgotten about 1.2. Good point!
