### ISSUE TITLE
multiCheckbox defaults to required

### ISSUE THREAD

**Issue by qinche** [formly-js/angular-formly-templates-bootstrap#37]
Whenever I check and then uncheck one of the checkboxes, the form will be set to invalid because `required: true`, even though I did not specify that in temaplateOptions. I believe this is a bug that needs to be fixed.

**Comment by kentcdodds** [comment]
Could you show an example? http://issue.angular-formly.com/

**Comment by qinche** [comment]
http://jsbin.com/niyoxe/edit?html,js,output here it is, modified from a previous issue.

**Comment by kentcdodds** [comment]
Ah, I see. You're right. I'm not sure what the issue is right off. I'll try to get to it soon, but I can't promise anything. If you (or anyone watching) could help to identify why this is happening (and even submit a PR) that would help a great deal.

**Comment by kentcdodds** [comment]
I'll release the fix as soon as I get to my laptop.

**Comment by kentcdodds** [comment]
Released as `5.0.2`
