### ISSUE TITLE
How can I add for example 'input-lg' bootstrap class to my input?

### ISSUE THREAD

**Issue by attilacsanyi** [formly-js/angular-formly-templates-bootstrap#39]
I would like to use input with 'input-lg' bootstrap class, can I override somewhere?
Thanks.

**Comment by benoror** [comment]
Yes! 
http://angular-formly.com/#/example/custom-types/custom-templates
http://angular-formly.com/#/example/custom-types/extending-types

**Comment by kentcdodds** [comment]
Going to go ahead and close this. If you have further questions, please see http://help.angular-formly.com

**Comment by kentcdodds** [comment]
Thanks @benoror!
