### ISSUE TITLE
angular-formly + dropzone.js

### ISSUE THREAD

**Issue by nelsontubaina** [formly-js/angular-formly-templates-bootstrap#44]
hey i've got a problem:

1 - I have a form using angular-formly (LOVE IT BTW);
2 - I use dropzone.js to upload files;
3- i have a input field in wich i'd like to populate once the dropzone gives me the event "addedfile" with the name of the file that has been added;

how do I do that? I THINK it would be with expressionProperties or a watch but I'm a angularjs newbie so I have no idea on how to do that.

**Comment by kentcdodds** [comment]
I'm super glad that you love angular-formly :-) That's really rewarding and validating for me!

I don't think `expressionProperties` is where you'd want to do this. You'll probably want to do this with either the `link` or `controller` function. I'm not sure how `dropzone.js` works, so I can't tell you for sure.

The best way to get help is to follow the instructions here: http://help.angular-formly.com.

The github issues are reserved for bugs and feature requests, so I'm going to close this. Good luck!

**Comment by nelsontubaina** [comment]
HEY MAN JUST TO TELL YOU, I MANAGED TO DO IT: HERE IS THE DEAL:

1 - I saw the first video on angular-formly on egghead.io then I saw that the field value is generated by the model;
2 - I created a value in said model with the name "flag" and the input I used had the key "flag" so it took the model property flag as initial value;
3 - I added a watch to the scope to changes made to flag. then I set it on the 'addedfile' event of dropzone and then I just go scope.digest

thats it!

many thx!

**Comment by kentcdodds** [comment]
Awesome! That's great :-) I'm glad you got it working! If you want, I'd love to have you make an example of what you did for the website. Here's how you do that: https://www.youtube.com/watch?v=4dsXXTPET4A&feature=youtu.be&list=PLV5CVI1eNcJi7lVVIuNyRhEuck1Z007BH

**Comment by nelsontubaina** [comment]
hey dude! I've posted the example, hope it helps! thx a lot for
angular-formly it rocks!

**Comment by kentcdodds** [comment]
Where's the link to the example? I haven't seen anything come in...

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by nelsontubaina** [comment]
http://output.jsbin.com/neyoko/
