### ISSUE TITLE
Why bower bootstrap dependency?

### ISSUE THREAD

**Issue by oswaldomilet** [formly-js/angular-formly-templates-bootstrap#50]
Why this template requires bootstrap as bower dependency?

I'm using only angular-bootstrap without jQuery, so when using wiredep to include bower files in index.html script tag, it's not being included cause I excluded bootstrap in wiredep configuration.

```
var wiredepConfig = {
  exclude: [/bootstrap.js$/, /bootstrap-sass\/.*\.js/, /bootstrap\.css/],
  directory: 'bower_components'
};
```

**Comment by kentcdodds** [comment]
Technically, this library wont work without bootstrap, hence the dependency. So you'll have to figure out how to make it work with your tool as is.

**Comment by browniebroke** [comment]
I also have the same issue, we use https://github.com/twbs/bootstrap-sass and https://github.com/ck86/main-bower-files to get the javascript sources to concatenate and minify. I'm having bootstrap.js included twice.

Would need to have some sort of optional dependency supported in Bower, but [they rejected](https://github.com/bower/bower/issues/391) the idea.

In case someone finds this, I resolved my problem by adding Bootstrap as dependency in my Bower file and utilizing [the `overrides` property](https://github.com/ck86/main-bower-files#overrides) from main-bower-files:
```json
{
  "dependencies": {
    "bootstrap-sass-official": "~3.3.7",
    "bootstrap": "~3.3.7",
  },
  "overrides": {
    "bootstrap": {
      "main": []
    }
  }
}
```
