### ISSUE TITLE
add optional sr-only to label 

### ISSUE THREAD

**Issue by shanemgrey** [formly-js/angular-formly-templates-bootstrap#51]
when sr-only is a class on the label, the label will hide for
non-screen-reader clients

I've made a feature branch to do this at https://github.com/shanemgrey/angular-formly-templates-bootstrap/tree/feature/sr-only

accepts an optional templateOption of labelSrOnly, which, if true, hides the label for
non-screen-reader clients

Only changes 2 lines of code (3 if you count the additional comma ;-)

Can you review my branch and let me know if you want a PR?

**Comment by kentcdodds** [comment]
Looks awesome. Feel free to PR.

**Comment by shanemgrey** [comment]
Thanks for merging!
