### ISSUE TITLE
Add peerDependencies to dependencies 

### ISSUE THREAD

**Issue by mhartington** [formly-js/angular-formly-templates-bootstrap#53]
With npm3, `peerDependencies` will not be auto installed unless they are also in your dependencies. 

https://github.com/formly-js/angular-formly-templates-bootstrap/blob/master/package.json#L35

**Comment by kentcdodds** [comment]
That's the idea. People using this should list those in their own dependencies. That way they can choose the version. This new behavior is desirable and I anticipated it in all my libraries :-)
