### ISSUE TITLE
Unable to use non standard angular start/stop symbols

### ISSUE THREAD

**Issue by davidlukerice** [formly-js/angular-formly-templates-bootstrap#60]
Due to server templating requirements, I've had to change the angular start and stop symbols from `{{ }}` to `[[ ]]`.
``` javascript
$interpolateProvider.startSymbol('[[').endSymbol(']]');
```

There's currently no way that I can find to change formly bootstrap to use other start/stop symbols other than manually editing the various `.html` templates.

**Comment by kentcdodds** [comment]
One thing that we could do is do a `replace ` on the template strings if the symbols are none-standard. This should be relatively trivial and might be a good first timer issue to...

**Comment by davidlukerice** [comment]
Good idea. I'm assuming that would be a change in [angular-formly](https://github.com/formly-js/angular-formly) and not in the template repos?

**Comment by kentcdodds** [comment]
Actually, no, this would happen in this repo. Anywhere we require a
template, we'd do a replace.

On Wed, Sep 30, 2015, 2:27 PM David Rice <notifications@github.com> wrote:

> Good idea. I'm assuming that would be a change in angular-formly
> <https://github.com/formly-js/angular-formly> and not in the template
> repos?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/formly-js/angular-formly-templates-bootstrap/issues/60#issuecomment-144531863>
> .
>
-- 
- Kent C. Dodds <https://twitter.com/kentcdodds>

**Comment by davidlukerice** [comment]
Seems a bit redundant to have to do it each time a template gets required. I'm currently just using 
```javascript
.run([ '$interpolate', 'formlyConfig', function($interpolate, formlyConfig) {
        formlyConfig.templateManipulators.postWrapper.push(function(template, options, scope) {
            return template.replace(/{{/g, $interpolate.startSymbol())
                           .replace(/}}/g, $interpolate.endSymbol());
        });
    }])
```
when I initialize my own app to get around the issue, so was assuming I could do something similar in angular-formly. Unless there's some performance hit that I'm not seeing.

**Comment by kentcdodds** [comment]
That's not what I mean. What I mean is, anywhere we do [this](https://github.com/formly-js/angular-formly-templates-bootstrap/blob/master/src/wrappers/index.js#L8):

```javascript
template: require('./label.html'),
```

We change it to:

```javascript
template: fixInterpolationSymbols(require('./label.html')),
```

where `fixInterpolationSymbols` is something like this:

```javascript
function fixInterpolationSymbols(templateString) {
  var start = $interpolate.startSymbol();
  var end =  $interpolate.endSymbol();
  if (start !== '{{') {
    templateString = templateString.replace(/{{/g, start);
  }
  if (end !== '}}') {
    templateString = templateString.replace(/{{/g, end);
  }
  return templateString;
}
```

**Comment by kentcdodds** [comment]
We'd put that function in a regular ES6 module and import it where we need it (so it'd need to accept the `$interpolate` as an additional argument).

**Comment by davidlukerice** [comment]
The import method still requires a code change every place a template is required, right (so 5 places in `angular-formly-templates-bootstrap`)? The module would also need to be duplicated across each `angular-formly-templates-*` repo and its template requires changed. This leaves quite a bit of room for bugs to slip in if a dev forgets to apply the fix method on a template import or if the method is updated in one template repo and not another. I understand the desire to leave templating concerns in the template extensions, but that much duplication makes me think the fix is at the wrong abstraction layer.

This is opposed to just having the single postWrapper push in say `angular-formly/src/run/updateInterpolateSymbols.js`.

``` javascript
export default updateInterpolateSymbols;

// @ngInject
function updateInterpolateSymbols(formlyConfig, $interpolate) {
  formlyConfig.templateManipulators.postWrapper.push(updateSymbols);

  function updateSymbols(template, options, scope) {
    var start = $interpolate.startSymbol();
    var end =  $interpolate.endSymbol();
    if (start !== '{{') {
      templateString = templateString.replace(/{{/g, start);
    }
    if (end !== '}}') {
      templateString = templateString.replace(/}}/g, end);
    }
    return templateString;
  }
}
```

The postWrapper seems designed for this sort of thing and looks like replacements would be more efficient, being called only once per form instead of once per template require.

**Comment by kentcdodds** [comment]
That makes sense. One issue I can see is that this will run for every field for every compile. While it's nice that you ensure you cover all the bases, it's sub-optimal from a perf standpoint. But that may be negligible.

That said, I don't want to put that in angular-formly core. A very small percentage of formly users will need it. But a plugin for that would be fantastic. Would you be interested in creating a plugin for that? See [here](http://docs.angular-formly.com/page/plugins) for more info.

**Comment by davidlukerice** [comment]
Oh, yah, that linking call is on the field and not the whole form. Makes sense to not want it in core. I can definitely throw it in a plugin.

**Comment by davidlukerice** [comment]
Would you prefer the plugin to reside in the formly-js org?

**Comment by kentcdodds** [comment]
I'll let you decide. I'll happily create the repo and add you as a collaborator if you like :-)

**Comment by davidlukerice** [comment]
Sure, that works for me. I'm assuming I can just mimic the structure of an existing plugin?

**Comment by kentcdodds** [comment]
Here's the repo: https://github.com/formly-js/angular-formly-dynamic-interpolate-symbols, you've been invited to collaborate on it.

You can feel free to do whatever you like with regards to the plugin. I don't recommend you go with the `kcd-common-tools` approach like some of the other plugins. It's a bit complex and not fully baked.

Feel free to do it however you like. Personally, I recommend you checkout my [How to Write an Open Source JavaScript Library](https://egghead.io/series/how-to-write-an-open-source-javascript-library) series on egghead, and then combine that knowledge with [Webpack](http://webpack.github.io/) ([egghead.io playlist](https://egghead.io/playlists/learning-webpack)).

Sorry that the original series isn't quite to webpack yet. Though you should be able to get away with doing this in a single file... If you want to DM me on twitter, I can give you access to a private video which could help you out as well..

**Comment by kentcdodds** [comment]
Oh, my twitter is: https://twitter.com/kentcdodds

**Comment by davidlukerice** [comment]
Alright, this feature is now in https://github.com/formly-js/angular-formly-dynamic-interpolate-symbols.

**Comment by kentcdodds** [comment]
This is terrific! I'll add it to the plugins page. Could you [make an example](https://youtu.be/4dsXXTPET4A?list=PLV5CVI1eNcJi7lVVIuNyRhEuck1Z007BH) for the website?

**Comment by kentcdodds** [comment]
[Added](http://docs.angular-formly.com/page/plugins)

**Comment by davidlukerice** [comment]
Alright. Put in a PR to add an example to the advanced tab.
https://github.com/formly-js/angular-formly-website/pull/81
