### ISSUE TITLE
ng-options not supported for non-select elements (e.g. ui-select) in Angular 1.4.x

### ISSUE THREAD

**Issue by mhazy** [formly-js/angular-formly-templates-bootstrap#61]
When creating a custom type that extends select, it uses the `ng-options` attribute, which is now strictly for \<select\> fields in Angular 1.4+. When ng-options is applied to other elements an error occurs (`Error: [$compile:ctreq] Controller 'select', required by directive 'ngOptions', can't be found!`).

The use case for this change would be using a custom select field like ui-select, as shown in the formly  example (http://angular-formly.com/#/example/integrations/ui-select).

I'm proposing that an additional configuration property be added for the select type to allow the attribute to be configurable. Defaulting the item to `ng-options` will keep it backwards compatible.

Suggested Change: mhazy/angular-formly-templates-bootstrap@5aff0c3d2d7c5b3b741d20924785d2e1bd11ddb8

**Comment by kentcdodds** [comment]
That commit would be a perfect pull request and I'd accept it in a heartbeat :heart:. Thanks! :smile:

**Comment by mhazy** [comment]
PR #62 Submitted, thanks!

**Comment by kentcdodds** [comment]
This has been automatically released as version `6.1.5`. Thanks! If you'd like, you could [create an example](https://youtu.be/4dsXXTPET4A?list=PLV5CVI1eNcJi7lVVIuNyRhEuck1Z007BH) for the website :-)
