### ISSUE TITLE
Update addOns to have a tab index

### ISSUE THREAD

**Issue by kentcdodds** [formly-js/angular-formly-templates-bootstrap#63]
From @Nishchit14 in https://github.com/formly-js/angular-formly/issues/501:

> Here i have to use two tab to go on next input field because of addons tabindex.
> 
> So if there is custom options for use tabindex for right/left addOns then it would so cool :)
> 
> And this is awesome :+1: 
> 
> ![image](https://cloud.githubusercontent.com/assets/5078921/10276316/4b4e0f34-6b6c-11e5-808c-51f308c22114.png)

Moving this to the proper repository.

I'm believe the tabindex gets added because of the [ng-click](https://github.com/formly-js/angular-formly-templates-bootstrap/blob/master/src/run/addons.html#L5). I think the real solution is to determine if the `ng-click` is necessary (if an `onClick` has been provided) and only add it if it is necessary. This would require additional logic [here](https://github.com/formly-js/angular-formly-templates-bootstrap/blob/master/src/run/addons.js#L22). I don't think that this would be a problem.

**Comment by cudasteve** [comment]
I can confirm ng-click is tacking on the tabindex.  In my implementation, I've changed it to use button addons per (this)[http://getbootstrap.com/components/#input-groups-buttons] when the ngClick option is present and use a simple span without ng-click when it's not present.  Tabs skip over non-clickable stuff and the addons look visibly clickable (and work with enter/spacebar) when they are clickable.

I'm off onto completely custom templates now, so a PR wouldn't be super easy at the moment, but hopefully the peanut gallery comment helps.
