### ISSUE TITLE
Add "maxlength" (and others?) to doc

### ISSUE THREAD

**Issue by estaub** [formly-js/angular-formly-templates-bootstrap#65]
I discovered that "maxlength" is supported by watching one of the videos... it would be good if it were documented on the readme, like the other templateOptions are.

**Comment by kentcdodds** [comment]
`maxlength` isn't a bootstrap specific templateOption. The options are [documented](http://docs.angular-formly.com/docs/ngmodelattrstemplatemanipulator), but could probably be made a little more obvious.
