### ISSUE TITLE
Add an empty option to Select

### ISSUE THREAD

**Issue by Luddinus** [formly-js/angular-formly-templates-bootstrap#67]
Hi.

Is this possible to add an empty option to the "select" type? Instead of doing a custom template...

```
<select ng-options="...">
   <option value="">-- Empty option --</option>
</select>
```

**Comment by Luddinus** [comment]
up

**Comment by kentcdodds** [comment]
I think we could probably update [the template](https://github.com/formly-js/angular-formly-templates-bootstrap/blob/master/src/types/select.js#L4) for the `select` type to support this. Something like this should do it:

```javascript
const template = `
  <select class="form-control" ng-model="model[options.key]">
    <option ng-hide="to.notNull" value="">{{to.nullDisplay}}</option>
  </select>
`;
```

If you'd like to create a [Pull Request](https://help.github.com/articles/using-pull-requests/) to add this functionality that would be cool.

I'd also like the [apiCheck definition](https://github.com/formly-js/angular-formly-templates-bootstrap/blob/master/src/types/select.js#L24-L28) to be updated to add the two new properties `notNull` is a boolean and `nullDisplay` is a string.

Also, adding these new properties to [the README.md](https://github.com/formly-js/angular-formly-templates-bootstrap/blob/master/README.md#select-form-field) would be great too.

**Comment by kentcdodds** [comment]
Oh, and once it's been released, [creating a new example](https://github.com/formly-js/angular-formly-website/blob/master/CONTRIBUTING.md#creating-an-example) would also be helpful

**Comment by Luddinus** [comment]
I guess would be better to set "nullable" instead of "notNull", and "nullableDisplay" instead of "nullDisplay"

**Comment by Luddinus** [comment]
I don't know how to put the examples, but this could be:

http://jsbin.com/kotacog/1/edit?js,output

**Comment by kentcdodds** [comment]
Did you see my comments on your pull requests? Could you it again? And I'd prefer it all to be in a single commit (rather than two)

**Comment by Luddinus** [comment]
@kentcdodds I'll check, I'm not use to pull requests etc. sorry

**Comment by kentcdodds** [comment]
You're fine! I'm actually an egghead.io author and will be making a series
on contributing to open source projects because it's hard for new comers.

**Comment by OskarPersson** [comment]
A combination of #68 and #69 has been created in #111 and is waiting to be merged.

**Comment by shmert** [comment]
I've found that if your model object property is `undefined` the select will choose the last item. If it's `null` you'll get an empty <option>
