### ISSUE TITLE
bower.json problem

### ISSUE THREAD

**Issue by weydran** [formly-js/angular-formly-templates-bootstrap#7]
there is something wrong in bower.json

dependencies
"angular-formly": "~1.0.0",
should be changed to new angular-formly version like "angular-formly": "~3.3.0",
It will make bower conflict error,please fix it.
thanks

**Comment by kentcdodds** [comment]
Thanks for letting me know. I'll get to that as soon as I am able.

**Comment by kentcdodds** [comment]
Fixed in 4.0.0
