### ISSUE TITLE
Remove nested watchers

### ISSUE THREAD

**Issue by kentcdodds** [formly-js/angular-formly-templates-bootstrap#70]
Inside the listener of a watcher, you shouldn't start another one. As we're doing [here](https://github.com/formly-js/angular-formly-templates-bootstrap/blob/master/src/types/multiCheckbox.js#L34-L49) cc @m0t0r this was added by [your commit](https://github.com/formly-js/angular-formly-templates-bootstrap/commit/909b33442cae1985ea0e3332b592e21051b9fd53) do you think you could look into fixing that?

**Comment by m0t0r** [comment]
Hey @kentcdodds, yes, I can take a look but most likely on Sunday.
