### ISSUE TITLE
Add HTML "type" option to templateOptions for formly input type

### ISSUE THREAD

**Issue by cudasteve** [formly-js/angular-formly-templates-bootstrap#72]
The idea is to have a templateOption to support passing through type="text" vs. type="number" vs. type="email" (and maybe api-check that they're passing a valid type?).

Maybe in practice, you'd want to create completely separate formly types for different types of data.  So maybe this would be encouraging bad habits.  But for folks using the bootstrap templates without modification, this would probably really help.

**Comment by kentcdodds** [comment]
This is [already supported](https://jsbin.com/qifimu/edit?html,js,output)

**Comment by cudasteve** [comment]
woops!  sorry, missed that.  good to know!
