### ISSUE TITLE
label seems to be optional but is required by the api check

### ISSUE THREAD

**Issue by ralphvanetten** [formly-js/angular-formly-templates-bootstrap#78]
As seen in https://github.com/formly-js/angular-formly-templates-bootstrap/issues/34 the label seems to be optional. But if I do not add a label to the fields, I see an apiCheck warning in the console.

It seems the label is not set to optional in https://github.com/formly-js/angular-formly-templates-bootstrap/blob/master/src/wrappers/index.js#L11

**Comment by Bookah** [comment]
This did not fix the warnings for me: 

  "shape": {
    "label": "String <-- YOU ARE MISSING THIS"
  }

Am I missing something?

**Comment by kentcdodds** [comment]
Hmmm.. Make sure you upgrade to the latest. [this example](https://jsbin.com/juxixe/edit?html,js,console,output) shows that it's working as expected.
