### ISSUE TITLE
Horizontal form

### ISSUE THREAD

**Issue by dmatesic** [formly-js/angular-formly-templates-bootstrap#8]
How would I make the form horizontal? http://getbootstrap.com/css/#forms-horizontal

**Comment by kentcdodds** [comment]
[Like this](http://formly-js.github.io/angular-formly/#/example/other/bootstrap-horizontal) :-)

**Comment by kentcdodds** [comment]
Let me know if you need any more help :-)

**Comment by markleusink** [comment]
Updated URL to that example: http://angular-formly.com/#/example/bootstrap-specific/bootstrap-horizontal

**Comment by kentcdodds** [comment]
:+1: thanks! Updating the original link as well.

**Comment by robrothedev** [comment]
Just started using Angular Formly about 3 hours ago and needed a horizontal form.  Talk about perfect timing :)   Got it working like a charm and added a horizontalSelect type to boot.  Thanks again!

**Comment by robrothedev** [comment]
One thing I did notice, however, is that the templateOptions: {required: true} not longer provides the asterisk next to the label.  I can manually add it to '{{to.label}} *' for a workaround in the setWrapper template.

**Comment by kentcdodds** [comment]
Yeah, I updated the example: http://angular-formly.com/#/example/bootstrap-specific/bootstrap-horizontal

**Comment by robrothedev** [comment]
Works great.  Thanks!

**Comment by tarkanlar** [comment]
how can i  make horizontalSelect  ?

**Comment by robrothedev** [comment]
Per the documentation added here: http://angular-formly.com/#/example/bootstrap-specific/bootstrap-horizontal you can add a formlyConfigProvider.setType({}) for a select. 

```
angular
	.module('app',['formly','formlyBootstrap'])
	.config(config);

function config(formlyConfigProvider) {
	// custom configuration for the formly templates
	formlyConfigProvider.setWrapper({
		name: 'horizontalBootstrapLabel',
		template: [
			'<label for="{{::id}}" class="col-sm-2 control-label">',
			'{{to.label}}  {{to.required ? "*" : ""}}',
			'</label>',
			'<div class="col-sm-9">',
			'<formly-transclude></formly-transclude>',
			'</div>'
		].join(' ')
	});

	// horizontal inputs
	formlyConfigProvider.setType({
		name: 'horizontalInput',
		extends: 'input',
		wrapper: ['horizontalBootstrapLabel', 'bootstrapHasError']
	});

	// horizontal selects
	formlyConfigProvider.setType({
		name: 'horizontalSelect',
		extends: 'select',
		wrapper: ['horizontalBootstrapLabel', 'bootstrapHasError']
	});
}
```

HTML

```
<form class="form-horizontal">
  <formly-form
     model="ctrl.form_model"
    fields="ctrl.form_fields">
  </formly-form>
</form>

**Comment by tarkanlar** [comment]
Thanks @robrothedev, i should have seen that , sorry

**Comment by robrothedev** [comment]
Not a problem and you're welcome.
