### ISSUE TITLE
Expression Properties don't seem to work when using Advanced Layout

### ISSUE THREAD

**Issue by keithmullins** [formly-js/angular-formly-templates-bootstrap#9]
This is my first issue here so firstly I'd just like to say that I love this library and thank you for creating / maintaining it. I have been using it in my latest project for the last few weeks and it has saved me a LOT of time.

I have come across an issue though. When using the Advanced Layout ( http://angular-formly.com/#/example/other/advanced-layout ) I can not seem to get the expressionProperties to work correctly. I have adjusted the code in the above example to set an expressionProperty on the lastName field to be disabled when the firstName field is blank:

`type: 'input',
key: 'lastName',
              templateOptions: {
                label: 'Last Name'
              },
              expressionProperties: {
                'templateOptions.disabled':'!model.firstName'  
              }`

The lastName becomes disabled but never becomes enabled once I start to enter text in the firstName field. I am having the same issue in my own project.

Is this a bug or something I am doing incorrectly ?

**Comment by kentcdodds** [comment]
Updated the example

Let me know if you still have questions :-) Glad that this library has been helpful to you!

**Comment by keithmullins** [comment]
Thank you - that worked a treat! :-)
